// data.js
export const foodPlans = [

 // พลังงาน 800-1000
 {
    energyRange: [800, 1000],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 4 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 0 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 3 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 3.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 1 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 3 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 3.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 1 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 3.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 0.5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 3 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 0 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 3 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 0 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 0 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 2.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 1 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 0 },
    ]
  },
  {
    energyRange: [800, 1000],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 2.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 1 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 2 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 0 },
    ]
  },

// พลังงาน 1001-1200
{
    energyRange: [1000, 1200],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 4 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 4 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 4 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 3.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 3 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 3.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 3.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2.5 },
    ]
  },
  {
    energyRange: [1000, 1200],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 3.5 },
      { type: "ผัก ก", total: 3 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2.5 },
    ]
  },

// พลังงาน 1201-1400
  {
    energyRange: [1201, 1400],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 5.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2 },
    ]
  },
{
    energyRange: [1201, 1400],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 3 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2.5 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 7 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 2 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 4 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 8 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1.5 },
    ]
  },
  {
    energyRange: [1201, 1400],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 4.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 7 },
      { type: "ผลไม้", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 4 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 1 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 1 },
    ]
  },
 
// พลังงาน 1401-1600
  {
    energyRange: [1401, 1600],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 6.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 6 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 6.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 6  },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1},
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5},
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 2 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 3.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 2.5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 5.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 3 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3.5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1401, 1600],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 6 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 4 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 2 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },

// พลังงาน 1601-1800
 {
    energyRange: [1601, 1800],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 9.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 8.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 8.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1.5 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1.5 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 1.5 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1601, 1800],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 1.5 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 4 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },

// พลังงาน 1801-2000
 {
    energyRange: [1801, 2000],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0.5 },
      { type: "ไขมัน", total: 10.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 8.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 9 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 9.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 6.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 9.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 4 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 7.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3.5 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 6.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 2 },
            { type: "ผัก ข", total: 3.5 },
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [1801, 2000],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 2 },
      { type: "ผัก ข", total: 3.5 },                                                                      
      { type: "ผลไม้", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 5.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },

// พลังงาน 2001-2200
  {
    energyRange: [2001, 2200],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 0 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 0 },
      { type: "ผลไม้", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 0 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 0 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 11 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 3 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 11 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 3 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5.5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 6.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 5.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 10.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 2 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total:  4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.75 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 2 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3.5 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 2 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 2 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2001, 2200],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 9.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 2 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },

// พลังงาน 2201-2400
 {
    energyRange: [2201, 2400],
    proteinRange: [40, 44],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 7 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0},
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 16 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 11 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [45, 49],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 9 },
      { type: "ผลไม้", total: 6 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 16 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 10 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [50, 54],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 6.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 14.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 10 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [55, 59],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 4 },
      { type: "ผลไม้", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 14.5},
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 8 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [60, 64],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 3 },
      { type: "ผลไม้", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 15 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 9 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1},
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 15 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 9 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 13.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 9 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 11 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 9 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 10 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 11.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 8 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 11 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 8 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 9 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 12 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 7 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 9.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 10 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 8.5 },
    ]
  },
  {
    energyRange: [2201, 2400],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 8 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 5.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 1 },
      { type: "นมไขมันเต็มส่วน", total: 0 },
      { type: "ไขมัน", total: 9.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 9 },
    ]
  },

// พลังงาน 2401-2600
 {
    energyRange: [2401, 2600],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 12 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 14.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2800],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 13 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 9 },
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 16 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2600],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 12.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 9 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1 },
      { type: "ไขมัน", total: 15 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2600],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 13 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 9 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
       { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 11.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2800],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 12 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 10 },
      { type: "ผลไม้", total: 3.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 10.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2600],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 12 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 10 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 2 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 11.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2600],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 12 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 11 },                                                                                                                    
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 4 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 12 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },
  {
    energyRange: [2401, 2600],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 12 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 10 },                                                                      
      { type: "ผลไม้", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 3 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 0 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 1.5 },
      { type: "ไขมัน", total: 12 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3 },
    ]
  },

// พลังงาน 2601-2800
{
    energyRange: [2601, 2800],
    proteinRange: [65, 69],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 10 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 5 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 5 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1.5 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 8 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4.5 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 17 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 7 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4.5 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 17 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4.5 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 6 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4.5 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },                                                                                                                              
      { type: "ผัก ข", total: 7 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4.5 },
    ]
  },
  {
    energyRange: [2601, 2800],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 3 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 2.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 1 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 6 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4.5 },
    ]
  },

// พลังงาน 2801-3000
{
    energyRange: [2801, 3000],
    proteinRange: [70, 74],
    portions: [
      { type: "ข้าว-แป้ง", total: 17 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 13 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [2801, 3000],
    proteinRange: [75, 79],
    portions: [
      { type: "ข้าว-แป้ง", total: 17 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 0.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 12.5 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3.5 },
    ]
  },
  {
    energyRange: [2801, 3000],
    proteinRange: [80, 84],
    portions: [
      { type: "ข้าว-แป้ง", total: 16.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 12 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [2801, 3000],
    proteinRange: [85, 89],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5.5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 2 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 11 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [2801, 3000],
    proteinRange: [90, 94],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 3 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 10 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 4 },
    ]
  },
  {
    energyRange: [2801, 3000],
    proteinRange: [95, 99],
    portions: [
      { type: "ข้าว-แป้ง", total: 16 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 0 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 10 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3.5 },
    ]
  },
  {
    energyRange: [2801, 3000],
    proteinRange: [100, 104],
    portions: [
      { type: "ข้าว-แป้ง", total: 15.5 },
      { type: "ผัก ก", total: 0 },
      { type: "ผัก ข", total: 5 },
      { type: "ผลไม้", total: 4 },
      { type: "เนื้อสัตว์ไขมันต่ำมาก", total: 0 },
      { type: "เนื้อสัตว์ไขมันต่ำ", total: 1.5 },
      { type: "เนื้อสัตว์ไขมันปานกลาง", total: 3 },
      { type: "เนื้อสัตว์ไขมันสูง", total: 2 },
      { type: "นมขาดมันเนย", total: 0 },
      { type: "นมพร่องมันเนย", total: 0 },
      { type: "นมไขมันเต็มส่วน", total: 2 },
      { type: "ไขมัน", total: 9 },
      { type: "น้ำตาลเพิ่มสำหรับประกอบอาหาร", total: 3.5 },
    ]
  },
];
